config/routes.rb
Rails.application.routes.draw do
  get 'admin'=>'admin#index'
  #get 'sessions/new'

  #get 'sessions/create'

  #get 'sessions/destroy'

  #get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

scope '(:locale)' do
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  get 'store/index'
  #post 'store/index'=>'store#index'
  root :to => 'store#index', :as => 'store'
  resources :products do
    get :who_bought, :on => :member
  end
end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag :application %>
<!-- END:stylesheet -->
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  <div id="banner">
    <%= form_tag store_path, :class => 'locale' ,:method => 'get' do %>
    <!-- END_HIGHLIGHT -->
    <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        :onchange => 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$$('.locale input').each(Element.hide)" %>
    <!-- START_HIGHLIGHT -->
    <% end %>
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title')%>
  </div>
  <div id="columns">
    <div id="side">
      <!-- START_HIGHLIGHT -->
      <!-- START:hidden_div -->
    <%if @cart%>
      <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
        <%= render @cart %>
      <% end %>
    <%end%>
    <!-- END:hidden_div -->
      <!-- END_HIGHLIGHT -->

      <!-- START_HIGHLIGHT -->
      <a href="http://www...."><%= t('.home') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../faq"><%= t('.questions') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../news"><%= t('.news') %></a><br />
<!-- END_HIGHLIGHT -->
<!-- START_HIGHLIGHT -->
      <a href="http://www..../contact"><%= t('.contact') %></a><br />
<!-- END_HIGHLIGHT -->
        <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders',   orders_path   %><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users',    users_path    %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete   %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>